// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KGfvAel_vaXO0h590v3NkxdTMrRwTxA',
    appId: '1:254163221221:web:b73ea36ca106d2acef320c',
    messagingSenderId: '254163221221',
    projectId: 'oddjob-app',
    authDomain: 'oddjob-app.firebaseapp.com',
    storageBucket: 'oddjob-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLfUJ7B2yUQIaR4u73zM2qBiTvUljmAM',
    appId: '1:254163221221:android:21aea2e3174a81caef320c',
    messagingSenderId: '254163221221',
    projectId: 'oddjob-app',
    storageBucket: 'oddjob-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhgZnqvy3MGs0j290oHY3CzefBvIWAoE',
    appId: '1:254163221221:ios:2d4faa084d25d70bef320c',
    messagingSenderId: '254163221221',
    projectId: 'oddjob-app',
    storageBucket: 'oddjob-app.appspot.com',
    iosBundleId: 'com.example.oddJobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAhgZnqvy3MGs0j290oHY3CzefBvIWAoE',
    appId: '1:254163221221:ios:b2b9b6d89b93b45cef320c',
    messagingSenderId: '254163221221',
    projectId: 'oddjob-app',
    storageBucket: 'oddjob-app.appspot.com',
    iosBundleId: 'com.example.oddJobApp.RunnerTests',
  );
}
